# Generated by Django 5.0.1 on 2024-02-04 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 14, 9, 3, 430473)),
            preserve_default=False,
        ),
    ]
