name: Demo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5430:5432

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - name: Install dependencies
      shell: bash
      run: poetry run poetry install

    - name: Run migrations
      shell: bash
      run: poetry run ./app/manage.py migrate

    - name: Restore database
      uses: tj-actions/pg-restore@v6
      with:
        database_url: "postgres://postgres:postgres@localhost:5432/postgres"
        backup_file: "seed-db.sql"
        postgresql_version: "16"

